# Generated by Django 5.1.2 on 2025-01-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_smartuser_phone_number_alter_smartuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartuser',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
